In [2]:
import torch

# ON CPU

In [3]:
x = torch.empty(2,2,3) # empty tensor (size) bach:2 height:2 width:2
x

tensor([[[-1.7733e-33,  4.5712e-41, -1.2933e-33],
         [ 4.5712e-41,  3.7698e+05,  2.8982e-32]],

        [[-1.7684e-33,  4.5712e-41, -1.2930e-33],
         [ 4.5712e-41,  3.1794e+17,  8.2923e+33]]])

In [4]:
x = torch.zeros(3,2,1) # zero tensors
x

tensor([[[0.],
         [0.]],

        [[0.],
         [0.]],

        [[0.],
         [0.]]])

In [5]:
x= torch.ones(2,2)
x

tensor([[1., 1.],
        [1., 1.]])

In [6]:
x = torch.rand(2,4,4,3) # random tensor (image) b2,h4,w4,c3
x

tensor([[[[0.0441, 0.1756, 0.7029],
          [0.1009, 0.3011, 0.7961],
          [0.6550, 0.8190, 0.2666],
          [0.9339, 0.2002, 0.9472]],

         [[0.6590, 0.8166, 0.9442],
          [0.6805, 0.1154, 0.9531],
          [0.1024, 0.5431, 0.4360],
          [0.8130, 0.9741, 0.2040]],

         [[0.1626, 0.5444, 0.8273],
          [0.8381, 0.8286, 0.3371],
          [0.0722, 0.4167, 0.5708],
          [0.6049, 0.8232, 0.7187]],

         [[0.8725, 0.4065, 0.5583],
          [0.0271, 0.4976, 0.5193],
          [0.7172, 0.3713, 0.6299],
          [0.0366, 0.9645, 0.2243]]],


        [[[0.9011, 0.5212, 0.6104],
          [0.0015, 0.0910, 0.3590],
          [0.9170, 0.8424, 0.7941],
          [0.2271, 0.7310, 0.5250]],

         [[0.9901, 0.4966, 0.1120],
          [0.4185, 0.0562, 0.9614],
          [0.9874, 0.7156, 0.4120],
          [0.6559, 0.1584, 0.2308]],

         [[0.1804, 0.3510, 0.4487],
          [0.0497, 0.1705, 0.9722],
          [0.7835, 0.2736, 0.2773],
          [0.0

In [7]:
x = torch.randn(2, 2) # random Normal tensor (image) b2,h4,w4,c3
x

tensor([[-0.4207,  0.7966],
        [-1.1666,  0.6328]])

In [8]:
x = torch.ones(2,2, dtype=torch.int) # int32
x

tensor([[1, 1],
        [1, 1]], dtype=torch.int32)

In [9]:
x = torch.rand(2,2, dtype=torch.double) # float64
print(x.size())
x.dtype

torch.Size([2, 2])


torch.float64

In [10]:
x = torch.tensor([2.5, 0.1]) # from a list
x

tensor([2.5000, 0.1000])

In [11]:
x = torch.tensor([[0.4, 0.8, 1.0],
                [0.3, 0.5, 0.7]])
y = torch.tensor([[0.5, 0.5, 0.1],
                [0.7, 0.3, 0.2]])
sum = x + y
sub = x - y
pointwise_mul = x * y
pointwise_div = x / y
# sum = torch.add(x, y)
# sub = torch.sub(x, y)
# mul = torch.mul(x, y)
# dev = torch.div(x, y)
print(sum)
print(sub)
print(pointwise_mul)
pointwise_div

tensor([[0.9000, 1.3000, 1.1000],
        [1.0000, 0.8000, 0.9000]])
tensor([[-0.1000,  0.3000,  0.9000],
        [-0.4000,  0.2000,  0.5000]])
tensor([[0.2000, 0.4000, 0.1000],
        [0.2100, 0.1500, 0.1400]])


tensor([[ 0.8000,  1.6000, 10.0000],
        [ 0.4286,  1.6667,  3.5000]])

In [12]:
""" x = torch.rand(2, 3)
y = torch.rand(2, 2) # shape mismatch!!
z = torch.add(x, y)
z """

' x = torch.rand(2, 3)\ny = torch.rand(2, 2) # shape mismatch!!\nz = torch.add(x, y)\nz '

In [13]:
x = torch.tensor([[0.4, 0.8, 1.0],
                [0.3, 0.5, 0.7]])
y = torch.tensor([[0.5, 0.5, 0.1],
                [0.7, 0.3, 0.2]])
y.add_(x) # inplace add, in PyTorch all inplace operations has a tailing underscore_
print(y)
y.sub_(x)
print(y)
y.mul_(x)
print(y)
y.div_(x)
y

tensor([[0.9000, 1.3000, 1.1000],
        [1.0000, 0.8000, 0.9000]])
tensor([[0.5000, 0.5000, 0.1000],
        [0.7000, 0.3000, 0.2000]])
tensor([[0.2000, 0.4000, 0.1000],
        [0.2100, 0.1500, 0.1400]])


tensor([[0.5000, 0.5000, 0.1000],
        [0.7000, 0.3000, 0.2000]])

In [14]:
print(x[1,1])
print(x[1,1].item())
print(x[:,1]) # slicing 2nd col
x[0,:] # 1st row

tensor(0.5000)
0.5
tensor([0.8000, 0.5000])


tensor([0.4000, 0.8000, 1.0000])

In [15]:
# reshaping
x = torch.tensor([[0.4, 0.8, 1.0],
                [0.3, 0.5, 0.7]])
y = torch.tensor([[0.5, 0.5, 0.1],
                [0.7, 0.3, 0.2]])

x_reshape = x.view(-1, 6) # -1 means infer the # rows from total # of items, I just care about # of col
print(x_reshape)
x_reshape = x.view(3, -1) # notice it's not transpose!!!! it first vectorize it, then creat the matrix again
print(x_reshape)
x_reshape = x.view(2, 3) # notice it's not transpose!!!! it first vectorize it, then creat the matrix again
print(x_reshape)

tensor([[0.4000, 0.8000, 1.0000, 0.3000, 0.5000, 0.7000]])
tensor([[0.4000, 0.8000],
        [1.0000, 0.3000],
        [0.5000, 0.7000]])
tensor([[0.4000, 0.8000, 1.0000],
        [0.3000, 0.5000, 0.7000]])


In [16]:
""" x_reshape = x.view(3,3) # mismatch shape """

' x_reshape = x.view(3,3) # mismatch shape '

In [17]:
import numpy as np

In [18]:
x_np = x.numpy()
# if the tensor is on the CPU (numpy does not work on GPU)
# and share the same memory location,
# then changing one will change the other
x_np

array([[0.4, 0.8, 1. ],
       [0.3, 0.5, 0.7]], dtype=float32)

In [19]:
x.add_(1)
print(x)
x_np

tensor([[1.4000, 1.8000, 2.0000],
        [1.3000, 1.5000, 1.7000]])


array([[1.4, 1.8, 2. ],
       [1.3, 1.5, 1.7]], dtype=float32)

In [20]:
x_np = np.ones([2,3])
x_np

array([[1., 1., 1.],
       [1., 1., 1.]])

In [21]:
x = torch.from_numpy(x_np).type(dtype=torch.int)
x

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)

In [22]:
x_np += np.ones([2,3])
print(x_np)
x

[[2. 2. 2.]
 [2. 2. 2.]]


tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)

# ON GPU

Notice: numpy can only handle CPU operations!!

In [23]:
# let's do it on GPU
if torch.cuda.is_available():
    cuda = torch.device("cuda")
    print(cuda)
    x = torch.rand([2,3], device=cuda) # creat it on GPU mem
    print(x)
    y = torch.rand([2,3]) # creat on CPU mem
    y = y.to(cuda) # move it to GPU mem
    print(y)
    z = x + y # torch.add(x, y) # it's done on GPU
    print(z) # z is on GPU mem

cuda
tensor([[0.8805, 0.6595, 0.7280],
        [0.0570, 0.8821, 0.4852]], device='cuda:0')
tensor([[0.8210, 0.7386, 0.3912],
        [0.4478, 0.8428, 0.6041]], device='cuda:0')
tensor([[1.7015, 1.3981, 1.1192],
        [0.5048, 1.7249, 1.0893]], device='cuda:0')


In [24]:
""" z = z.numpy() # error
z """
z = z.to(device='cpu')
z.numpy()
z

tensor([[1.7015, 1.3981, 1.1192],
        [0.5048, 1.7249, 1.0893]])

In [25]:
# when you have variable that you want to calc gradient later
# like your loss, weights or latent cariable,
# set another argument to True
x = torch.ones(5, requires_grad=True)
x

tensor([1., 1., 1., 1., 1.], requires_grad=True)